<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Consumable Transfer #{{ $transfer->id }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10pt;
            color: #1a1a1a;
            line-height: 1.5;
        }

        @page {
            margin-left: 15mm;
            margin-right: 15mm;
            footer: mainFooter;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            border-spacing: 0;
        }

        .header-section {
            margin-bottom: 30px;
        }

        .company-name {
            font-size: 18pt;
            font-weight: bold;
            color: #000;
            margin-bottom: 5px;
        }

        .company-address {
            font-size: 9pt;
            color: #555;
            line-height: 1.4;
        }

        .doc-title {
            font-size: 20pt;
            font-weight: bold;
            color: #333;
            text-transform: uppercase;
            text-align: right;
            margin-bottom: 5px;
        }

        .doc-meta {
            text-align: right;
            font-size: 9.5pt;
            color: #555;
            line-height: 1.4;
        }

        .info-table {
            margin-bottom: 30px;
        }

        .info-table td {
            vertical-align: top;
            padding: 0;
        }

        .info-title {
            font-size: 9pt;
            font-weight: bold;
            color: #666;
            text-transform: uppercase;
            border-bottom: 1px solid #ddd;
            padding-bottom: 3px;
            margin-bottom: 5px;
            width: 90%;
            display: block;
        }

        .items-table {
            width: 100%;
            margin-top: 20px;
            border: 1px solid #e0e0e0;
        }

        .items-table th {
            background-color: #f8f8f8;
            color: #333;
            font-weight: bold;
            padding: 12px 8px;
            text-align: left;
            border-bottom: 1px solid #ccc;
            font-size: 9pt;
            text-transform: uppercase;
        }

        .items-table td {
            padding: 10px 8px;
            border-bottom: 1px solid #eee;
            color: #333;
            font-size: 9.5pt;
            vertical-align: middle;
        }

        .text-right  { text-align: right; }
        .text-center { text-align: center; }
        .font-bold   { font-weight: bold; }

        .summary-box {
            margin-top: 25px;
            border: 1px solid #e0e0e0;
            border-radius: 4px;
            padding: 12px 15px;
            width: 40%;
            margin-left: auto;
            background-color: #f9fafb;
        }

        .summary-row {
            display: table;
            width: 100%;
            padding: 4px 0;
        }

        .summary-label {
            display: table-cell;
            color: #666;
            width: 60%;
        }

        .summary-value {
            display: table-cell;
            text-align: right;
            font-weight: bold;
        }
    </style>
</head>
<body>

    <htmlpagefooter name="mainFooter">
        <table width="100%" style="font-size: 8pt; border: none;">
            <tr>
                <td align="left" style="border: none;">
                    Consumable Transfer generated by Skin Genious CRM.
                </td>
                <td align="right" style="border: none;">
                    Page {PAGENO} / {nbpg}
                </td>
            </tr>
        </table>
    </htmlpagefooter>

    <table class="header-section">
        <tr>
            <td width="60%" valign="top">
                <div class="company-name">{{ $clinic->name ?? 'Skin Genious CRM' }}</div>
                <div class="company-address">
                    {{ $clinic->address_line1 ?? '' }}<br>
                    {{ $clinic->city ?? '' }}@if($clinic->pincode ?? null) - {{ $clinic->pincode }}@endif<br>
                    @if($clinic->gst_number ?? null)<strong>GSTIN:</strong> {{ $clinic->gst_number }}<br>@endif
                    @if($clinic->email ?? null)<strong>Email:</strong> {{ $clinic->email }}@endif
                    @if($clinic->phone ?? null) | <strong>Phone:</strong> {{ $clinic->phone }}@endif
                </div>
            </td>
            <td width="40%" valign="top">
                <div class="doc-title">CONSUMABLE<br>TRANSFER</div>
                <div class="doc-meta">
                    Transfer #: <strong>{{ $transfer->id }}</strong><br>
                    Date: <strong>{{ $transfer->transfer_date ? $transfer->transfer_date->format('d M, Y') : 'N/A' }}</strong><br>
                    Author: <strong>{{ $transfer->creator->first_name ?? 'N/A' }}</strong>
                </div>
            </td>
        </tr>
    </table>

    @if($transfer->notes)
    <table class="info-table">
        <tr>
            <td width="100%">
                <span class="info-title">Notes / Description</span>
                {{ $transfer->notes }}
            </td>
        </tr>
    </table>
    @endif

    <table class="items-table" cellspacing="0" cellpadding="0">
        <thead>
            <tr>
                <th width="5%"  class="text-center">#</th>
                <th width="55%">Product</th>
                <th width="15%" class="text-center">Type</th>
                <th width="15%" class="text-center">Unit</th>
                <th width="10%" class="text-center">Qty Used</th>
            </tr>
        </thead>
        <tbody>
            @foreach($items as $index => $item)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td><span class="font-bold">{{ $item->product->name ?? '—' }}</span></td>
                <td class="text-center" style="font-size:8pt; color:#666;">
                    {{ ucfirst(str_replace('_', ' ', $item->product->type ?? '')) }}
                </td>
                <td class="text-center">{{ $item->product->unit ?? '—' }}</td>
                <td class="text-center font-bold">{{ $item->quantity_used }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="summary-box">
        <div class="summary-row">
            <span class="summary-label">Total Unique Products</span>
            <span class="summary-value">{{ $items->count() }}</span>
        </div>
        <div class="summary-row">
            <span class="summary-label">Total Qty Consumed</span>
            <span class="summary-value">{{ $items->sum('quantity_used') }}</span>
        </div>
    </div>

</body>
</html>
