<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Purchase Order #{{ $purchase->id }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10pt;
            color: #1a1a1a;
            line-height: 1.5;
        }

        @page {
            margin-left: 15mm;
            margin-right: 15mm;
            footer: mainFooter;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            border-spacing: 0;
        }

        .header-section {
            margin-bottom: 30px;
        }

        .company-name {
            font-size: 18pt;
            font-weight: bold;
            color: #000;
            margin-bottom: 5px;
        }

        .company-address {
            font-size: 9pt;
            color: #555;
            line-height: 1.4;
        }

        .invoice-title {
            font-size: 22pt;
            font-weight: bold;
            color: #333;
            text-transform: uppercase;
            text-align: right;
            margin-bottom: 5px;
        }

        .invoice-meta {
            text-align: right;
            font-size: 9.5pt;
            color: #555;
            line-height: 1.4;
        }

        .info-table {
            margin-bottom: 30px;
        }

        .info-table td {
            vertical-align: top;
            padding: 0;
        }

        .info-title {
            font-size: 9pt;
            font-weight: bold;
            color: #666;
            text-transform: uppercase;
            border-bottom: 1px solid #ddd;
            padding-bottom: 3px;
            margin-bottom: 5px;
            width: 90%;
            display: block;
        }

        .items-table {
            width: 100%;
            margin-top: 20px;
            border: 1px solid #e0e0e0;
        }

        .items-table th {
            background-color: #f8f8f8;
            color: #333;
            font-weight: bold;
            padding: 12px 8px;
            text-align: left;
            border-bottom: 1px solid #ccc;
            font-size: 9pt;
            text-transform: uppercase;
        }

        .items-table td {
            padding: 10px 8px;
            border-bottom: 1px solid #eee;
            color: #333;
            font-size: 9.5pt;
            vertical-align: middle;
        }

        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .font-bold { font-weight: bold; }

        .totals-container {
            width: 100%;
            margin-top: 20px;
        }

        .totals-table {
            width: 45%;
            margin-left: auto;
        }

        .totals-table td {
            padding: 6px 0;
            text-align: right;
        }

        .totals-table .label {
            color: #666;
            padding-right: 15px;
            width: 60%;
        }

        .grand-total-row td {
            padding-top: 10px;
            border-top: 2px solid #333;
        }

        .grand-total-label, .grand-total-value {
            font-size: 11pt;
            font-weight: bold;
            color: #000;
        }

        .status-paid { color: #16a34a; font-weight: bold; }
        .status-unpaid { color: #dc2626; font-weight: bold; }
    </style>
</head>
<body>

    <htmlpagefooter name="mainFooter">
        <table width="100%" style="font-size: 8pt; border: none;">
            <tr>
                <td align="left" style="border: none;">
                    Purchase Order generated by Skin Genious CRM.
                </td>
                <td align="right" style="border: none;">
                    Page {PAGENO} / {nbpg}
                </td>
            </tr>
        </table>
    </htmlpagefooter>

    <table class="header-section">
        <tr>
            <td width="60%" valign="top">
                <div class="company-name">{{ $clinic->name }}</div>
                <div class="company-address">
                    {{ $clinic->address_line1 }}<br>
                    {{ $clinic->city }} - {{ $clinic->pincode }}<br>
                    <strong>GSTIN:</strong> {{ $clinic->gst_number }}<br>
                    <strong>Email:</strong> {{ $clinic->email }} | <strong>Phone:</strong> {{ $clinic->phone }}
                </div>
            </td>
            <td width="40%" valign="top">
                <div class="invoice-title">PURCHASE ORDER</div>
                <div class="invoice-meta">
                    Order #: <strong>{{ $purchase->id }}</strong><br>
                    Date: <strong>{{ $purchase->purchase_date ? $purchase->purchase_date->format('d M, Y') : 'N/A' }}</strong><br>
                    Status: <span class="status-{{ strtolower($purchase->status) }}">{{ ucfirst($purchase->status) }}</span>
                </div>
            </td>
        </tr>
    </table>

    <table class="info-table">
        <tr>
            <td width="55%" valign="top">
                <div class="info-box">
                    <div class="info-title">Supplier Information</div>
                    <div class="client-info">
                        <strong>{{ $purchase->supplier_name }}</strong>
                    </div>
                </div>
            </td>
            <td width="45%" valign="top">
                <div class="info-box">
                    <div class="info-title">Order Details</div>
                    <div class="payment-info">
                        Payment: {{ ucfirst($purchase->payment_mode) }}<br>
                        @if($purchase->notes)
                        Notes: {{ $purchase->notes }}
                        @endif
                    </div>
                </div>
            </td>
        </tr>
    </table>

    <table class="items-table" cellspacing="0" cellpadding="0">
        <thead>
            <tr>
                <th width="5%" class="text-center">#</th>
                <th width="40%">Item Description</th>
                <th width="10%" class="text-center">Qty</th>
                <th width="15%" class="text-right">Rate</th>
                <th width="15%" class="text-right">GST</th>
                <th width="15%" class="text-right">Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($items as $index => $item)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td>
                    <span class="font-bold">{{ $item->product->name }}</span>
                </td>
                <td class="text-center">{{ $item->quantity }}</td>
                <td class="text-right">₹{{ number_format($item->purchase_price, 2) }}</td>
                <td class="text-right">
                    <div style="font-size: 8pt; color: #666;">{{ $item->gst }}%</div>
                    <div>₹{{ number_format($item->gst_amount, 2) }}</div>
                </td>
                <td class="text-right font-bold">₹{{ number_format($item->total, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="totals-container">
        <table class="totals-table">
            <tr>
                <td class="label">Subtotal (Taxable)</td>
                <td class="value">₹{{ number_format($purchase->subtotal, 2) }}</td>
            </tr>
            @if($purchase->total_discount > 0)
            <tr>
                <td class="label">Total Discount</td>
                <td class="value" style="color: green;">- ₹{{ number_format($purchase->total_discount, 2) }}</td>
            </tr>
            @endif
            <tr>
                <td class="label">Total GST</td>
                <td class="value">₹{{ number_format($purchase->total_gst, 2) }}</td>
            </tr>
            <tr class="grand-total-row">
                <td class="grand-total-label">Grand Total</td>
                <td class="grand-total-value">₹{{ number_format($purchase->total_amount, 2) }}</td>
            </tr>
        </table>
    </div>
</body>
</html>
