// Shared baseline/comparison semantics. No patient-specific scores or gain multipliers.
export const APPEARANCE_CONTRACT_VERSION='aia_visible_appearance_contract_v3.17.0'
export const APPEARANCE_INSTRUCTIONS=`VISIBLE APPEARANCE CONTRACT V3.17
The client-facing numerical parameter describes the appearance a clinician can observe in white light, relative to an excellent realistic appearance for that parameter and the person's natural skin tone. It is not a disease grade, population percentile, instrument reading or measurement of tissue composition. Inspect white first, then the other permitted modes to identify findings and resolve ambiguity. White is the primary appearance reference; surface/subsurface modes are supporting views, not equal votes. Preserve non-white findings in the appropriate feature evidence for clinical planning.

Do not let a persistent UV pattern or a more conspicuous cross-polarized pattern alone veto a clearly supported change in white-light pigment appearance. Conversely, do not ignore corroborating evidence that an apparent change is glare, external material, concealment or a different anatomical location. If white skin appearance is obscured, report a supported estimate only when other visible evidence supports it and describe the limitation. Confidence never changes the numerical severity. No automatic mode-disagreement penalty.

Judge conspicuousness at ordinary full-face viewing scale AND inspect relevant regions for its cause. Tiny details revealed only by magnification should not dominate a client appearance score. A conspicuous localized patch or congested nose must not be averaged away by normal skin elsewhere. Regional extent is context, not a multiplier. Do not count one finding twice within a parameter merely because it is described by two features. Shared features can legitimately affect different parameters, but each needs its own appearance-based explanation.

Use the full continuous 0..5 impact scale and the parameter's supplied anchors. Mild, moderate and marked refer to VISIBLE IMPACT, not medical severity. A non-inflamed but visibly dull, uneven or rough face can have appreciable cosmetic impact. High appearance scores require positively good appearance; absence of severe disease does not establish excellence. Interpolate between neighbouring anchors using the residual concern actually visible. There is no required population distribution, expected treatment gain, patient target, or minimum improvement.

GLOW: broad diffuse luminosity, less grayness and clarity/evenness of visible tone, including reduced pigment conspicuousness. Compare non-glare skin against the person's natural tone. Oily hotspots and isolated product glints are not brightness credit. Reduced oily shine can coexist with improved glow. Do not equate glow with hydration: a large supported glow shift does not force a hydration shift.
VISIBLE PIGMENTATION: patch darkness relative to adjacent same-region skin, edge conspicuousness and how strongly brown unevenness interrupts the visible tone. A patch can remain in the same area yet become much less conspicuous. This score describes visible pigment appearance, not melanin removal, depth or durable clearance. Whole-image brightness alone is insufficient; explain the same patch's local contrast and appearance. Keep UV optical context separate.
TEXTURE AND PORES: include fine AND coarse roughness, pore prominence, visible congestion, pits and scars. Fine-grain improvement can improve surface quality even when pore size is unchanged. Do not require all components to change. Do not reward absent scars as cancellation of prominent congestion. Structural scar components stay fixed in immediate reassessment; do not claim scar repair from smoother surface reflection.
TEXTURAL RADIANCE: fine grain, fine relief shadows and continuity of broad surface reflection. Evaluate the smoothness of the visible finish, not raw brightness. Fine texture may contribute both here and to texture/pores, with distinct explanations; it is not exclusive to this parameter.
ACNE: separately inspect recognizable open/closed comedones and inflammatory papules/pustules/swellings. Meaningful visible congestion counts even without inflammation. A partly cleared cluster can improve while some dots persist. Do not equate all dark dots with blackheads or flat reactive redness with new papules. Explain real opposing changes rather than automatically letting one red spot cancel reduced congestion.
HYDRATION APPEARANCE: positive superficial plumpness/freshness, fine dehydration-line softening, crepiness and genuinely dry patches. Absence of flakes alone does not establish ideal hydration; gloss alone does not establish skin water or improvement. Do not infer hydration gains from pigment or glow gains.

CAPTURE: use corresponding anatomy and comparable viewing scale. Do not assume lighting changed to discount a difference. Do account for visible pose, obstruction, focus and glare. Crops, when explicitly supplied, add local evidence but do not replace whole-face context; never claim a crop, count or registration that was not supplied. No inferred feel, symptoms, water content, elasticity or treatment success.`

export function applyAppearanceDefinitions(features,parameters){
 features.roughness.definition='Visible fine AND coarse uneven surface relief, including grainy micro-roughness outside pore openings and fixed scar depressions. Fine surface smoothing counts even when pore size is unchanged.'
 features.pigment_contrast.definition='White-light conspicuousness of brown patches/freckles against nearby same-region skin: darkness, edge contrast and visible tone interruption. Subsurface helps identify the finding; UV is separate context. Exclude natural tone, moles, hair/pore shadows, redness and glare.'
 features.diffuse_dullness.definition='Loss of broad diffuse luminosity/clarity or gray appearance in white light relative to natural skin tone, outside oily hotspots and product glints. Inspect overall appearance and corresponding exposed skin.'
 features.comedones.definition='Recognizable open/closed comedones and clustered plugged openings: conspicuousness and congestion in matched regions, not mere dot presence. Exclude normal sebaceous filaments, unblocked pores, pigment and hair; no invented counts.'
 parameters.skin_luminosity_glow.definition='White-light diffuse luminosity, clarity and visible tone evenness, including how pigment disrupts the luminous impression. Oily hotspots earn no brightness credit; hydration is a distinct appearance judgment.'
 parameters.superficial_pigmentation.definition='Conspicuousness of visible brown unevenness in white light relative to local natural skin tone; assess patch contrast, edges and tone interruption. Supporting optical modes identify context, not a measurement of melanin clearance.'
 parameters.texture_open_pores.definition='Visible surface quality including fine/coarse roughness, conspicuous pores, congestion, pits and scars. Fine surface smoothing can improve this score with unchanged pore size or scars. Normal pores are allowed.'
 parameters.texture_open_pores.features=[...new Set([...parameters.texture_open_pores.features,'micrograin','microshadows'])]
 // These qualitative anchors are hypotheses to validate across clients, not fitted patient endpoints.
 const anchors={
  skin_luminosity_glow:['Broadly clear, even diffuse luminosity with only slight residual dullness or tone interruption.','Clearly limited luminosity and/or visible uneven tone affects the face despite absence of severe disease.','Strongly dull/gray or visibly uneven appearance substantially limits luminosity; need not involve the whole face.'],
  superficial_pigmentation:['Faint residual patch contrast with modest interruption of otherwise even visible tone.','Readily conspicuous brown patch contrast or mottling interrupts visible tone, including a localized forehead/cheek patch.','Strong patch contrast/edges or mottling substantially interrupts visible evenness, even if localized.'],
  texture_open_pores:['Mostly smooth visible surface with mild residual grain, openings or congestion.','Readily noticeable fine/coarse roughness, conspicuous pores, congestion or pits disrupts surface quality in key regions.','Strongly conspicuous roughness, congestion, pores or pits substantially disrupts visible surface quality.'],
  textural_radiance:['Mostly continuous smooth surface reflection with slight residual grain or microshadows.','Readily visible grain or interrupted broad reflection limits the smooth, refined surface impression.','Strongly grainy or discontinuous surface reflection substantially limits the refined appearance.']
 }
 for(const[id,[mild,moderate,marked]]of Object.entries(anchors))Object.assign(parameters[id].anchors,{mild,moderate,marked})
 for(const p of Object.values(parameters)){
  p.modes=['white',...p.modes.filter(m=>m!=='white')]
  p.primary_modes=['white'];p.support_modes=p.modes.filter(m=>m!=='white')
  p.appearance_contract=APPEARANCE_CONTRACT_VERSION
 }
}
