import assert from 'node:assert/strict'
import {FEATURES,PARAMETER_WEIGHTS,scoreParameter,FORMULA_VERSION,MEASUREMENT_VERSION,observationBurden} from './baselineScoringV314.js'
import {GROUPS,groupWeight,decodeMeasurements,measurementPrompt} from './regionalMeasurementV310.js'
import {buildRegionalRun} from './regionalScoringV310.js'
import {buildSkinAnalysisReportV3} from './buildSkinAnalysisReportV3.js'
import {buildLegacyDiagnosisV34} from './legacyFacialAdapterV34.js'
export function fixture(severity=.45,extent=1){return {version:MEASUREMENT_VERSION,regions:Object.fromEntries(Object.keys(GROUPS).map(g=>[g,{visible_fraction:1,obstruction_note:''}])),observations:Object.fromEntries(Object.entries(FEATURES).map(([f,c])=>[f,Object.fromEntries(c.regions.map(g=>[g,{severity,extent:severity===0?0:extent,confidence:.9,estimated:false,evidence:'Synthetic finding; not patient data.'}]))])),skin_type:{label:'balanced',confidence:.9,observation:'Synthetic fixture'}}}
const options={scanId:'assessment-0-baseline',imageSetHash:'synthetic',modelVersion:'mock'}
const run=x=>buildRegionalRun(x,options).skin_state
const checks=[]
function check(name,f){f();checks.push(name)}
const f=fixture(),base=run(f)
check('Every parameter has valid normalized fixed weights',()=>{for(const w of Object.values(PARAMETER_WEIGHTS))assert(Math.abs(Object.values(w).reduce((a,b)=>a+b,0)-1)<1e-12)})
check('Identical evidence gives identical scores and audits',()=>assert.deepEqual(base.derived_report_parameters,run(f).derived_report_parameters))
check('Confidence does not change scores or planning burdens',()=>{const x=structuredClone(f);for(const rows of Object.values(x.observations))for(const r of Object.values(rows))r.confidence=.2;const y=run(x);for(const id of Object.keys(PARAMETER_WEIGHTS))assert.equal(y.derived_report_parameters[id].display_score_1_to_100,base.derived_report_parameters[id].display_score_1_to_100);for(const id of Object.keys(y.core_features))assert.equal(y.core_features[id].global_burden_score_1_to_100,base.core_features[id].global_burden_score_1_to_100)})
check('Normal/absent concerns map to 100; maximal burden to 1 for all scores',()=>{for(const [s,expected]of [[0,100],[1,1]]){const x=run(fixture(s));for(const id of Object.keys(PARAMETER_WEIGHTS))assert.equal(x.derived_report_parameters[id].display_score_1_to_100,expected)}})
check('Every included component worsens its parameter monotonically',()=>{for(const[id,w]of Object.entries(PARAMETER_WEIGHTS))for(const feature of Object.keys(w)){const x=structuredClone(f);for(const r of Object.values(x.observations[feature]))r.severity=.65;assert(scoreParameter(id,x.observations,groupWeight).health<scoreParameter(id,f.observations,groupWeight).health)}})
check('A severe deep inflammatory finding cannot be diluted to a healthy acne score',()=>{const x=fixture(0);for(const r of Object.values(x.observations.deep_inflammatory_lesions)){r.severity=1;r.extent=1}assert(run(x).derived_report_parameters.visual_acne.display_score_1_to_100<50)})
check('Extent is monotonic, but a small local finding is not full-region burden',()=>{assert(observationBurden({severity:.7,extent:.04})<observationBurden({severity:.7,extent:.25}));assert(observationBurden({severity:.7,extent:.25})<.7)})
check('Crepiness and plumpness deficits lower hydration even without flakes or dry patches',()=>{const x=fixture(0);for(const feature of ['crepiness','plumpness_deficit'])for(const r of Object.values(x.observations[feature])){r.severity=.7;r.extent=1}assert(run(x).derived_report_parameters.skin_hydration.display_score_1_to_100<80)})
check('Oil film cannot brighten glow, improve hydration or alter measured pore prominence',()=>{const x=structuredClone(f);for(const r of Object.values(x.observations.oily_film))r.severity=.9;const y=run(x);for(const id of ['skin_luminosity_glow','skin_hydration','texture_open_pores'])assert.deepEqual(y.derived_report_parameters[id],base.derived_report_parameters[id]);assert(y.derived_report_parameters.skin_sebum.display_score_1_to_100<base.derived_report_parameters.skin_sebum.display_score_1_to_100)})
check('Pits/scars affect texture independently of fine radiance',()=>{const x=structuredClone(f);x.observations.scars_pits.cheek_left.severity=.9;const y=run(x);assert(y.derived_report_parameters.texture_open_pores.display_score_1_to_100<base.derived_report_parameters.texture_open_pores.display_score_1_to_100);assert.equal(y.derived_report_parameters.textural_radiance.display_score_1_to_100,base.derived_report_parameters.textural_radiance.display_score_1_to_100)})
check('Pigment contrast lightening improves pigment and glow using one observation',()=>{const x=structuredClone(f);x.observations.pigment_contrast.forehead_center.severity=.1;const y=run(x);for(const id of ['superficial_pigmentation','skin_luminosity_glow'])assert(y.derived_report_parameters[id].calibration.unrounded_health_1_to_100>base.derived_report_parameters[id].calibration.unrounded_health_1_to_100)})
check('Continuous interpolation reaches every integer from 61 through 77',()=>{for(let score=61;score<=77;score++)assert.equal(run(fixture((100-score)/99)).derived_report_parameters.skin_hydration.display_score_1_to_100,score)})
check('Structural components are explicitly identified for next reassessment phase',()=>{assert(base.derived_report_parameters.texture_open_pores.calibration.structural_components.includes('scars_pits'));assert.equal(base.derived_report_parameters.jawline_sagging.calibration.structural_components.length,3)})
check('Missing, nonfinite, unsupported, malformed and old-version observations are rejected',()=>{for(const mutate of [x=>delete x.observations.crepiness.cheek_left,x=>x.observations.crepiness.cheek_left.severity=NaN,x=>x.observations.crepiness.cheek_left.confidence=0,x=>x.observations.crepiness.cheek_left.extent=0,x=>x.version='old',x=>x.observations.crepiness.cheek_left.unexpected=1]){const x=structuredClone(f);mutate(x);assert.throws(()=>decodeMeasurements(x))}})
check('UV pattern does not change any client score or imply measured pigment depth',()=>{const x=structuredClone(f);for(const r of Object.values(x.observations.uv_pigment_pattern))r.severity=.9;const y=run(x);assert.deepEqual(y.derived_report_parameters,base.derived_report_parameters);assert.notEqual(y.core_features.underlying_pigment_support.global_burden_score_1_to_100,base.core_features.underlying_pigment_support.global_burden_score_1_to_100)})
check('Report cards and compatibility diagnosis share canonical baseline scores',()=>{const report=buildSkinAnalysisReportV3({skinState:base});const d=buildLegacyDiagnosisV34({skinAnalysisReport:report,skinState:base});for(const card of report.primary_client_assessment.parameter_cards){if(card.parameter_id==='skin_type')continue;assert.equal(Math.round(card.client_health_score_1_to_100),base.derived_report_parameters[card.parameter_id].display_score_1_to_100)}assert(d)})
console.log(JSON.stringify({ok:true,checks,measurement_version:MEASUREMENT_VERSION,formula_version:FORMULA_VERSION,prompt_characters:measurementPrompt().length,fixture_response_bytes:Buffer.byteLength(JSON.stringify(f)),scope:'Synthetic software validation only; no live vision, clinical accuracy, population calibration or fresh-run repeatability claim.'},null,2))
