import {createHash} from 'node:crypto';
import {VERSION,FORMULA_VERSION,PARAMETERS,IDS,REGIONS,DEFAULT_CALIBRATION} from './componentContractV318.js';
import {decodeMeasurements} from './componentMeasurementV318.js';
import {SKIN_STATE_SCHEMA_VERSION,VISION_EVIDENCE_SCHEMA_VERSION} from './skinStateV2.schema.js';
import {FACE_ZONE_ATLAS_VERSION} from './faceZoneAtlasV2.js';
export function validateCalibration(c){if(!c||c.version!==FORMULA_VERSION||!['rms','mean'].includes(c.aggregation)||!c.gamma||Object.keys(c.gamma).sort().join()!==[...IDS].sort().join())throw Error('Invalid V3.18 calibration');for(const g of Object.values(c.gamma))if(typeof g!=='number'||!Number.isFinite(g)||g<.5||g>2)throw Error('Gamma must be a finite number in 0.5..2');return c;}
export function calibrationIdentity(c){validateCalibration(c);return createHash('sha256').update(JSON.stringify({version:c.version,aggregation:c.aggregation,gamma:IDS.map(id=>[id,c.gamma[id]])})).digest('hex');}
export function combineComponents(id,values,aggregation='rms'){
 const w=PARAMETERS[id]?.components;if(!w||Object.keys(values).sort().join()!==Object.keys(w).sort().join())throw Error('Invalid components '+id);
 if(Object.values(values).some(x=>typeof x!=='number'||!Number.isFinite(x)||x<0||x>1))throw Error('Invalid component severity '+id);
 if(!['rms','mean'].includes(aggregation))throw Error('Unknown aggregation');
 const sum=Object.entries(w).reduce((s,[k,a])=>s+a*(aggregation==='rms'?values[k]**2:values[k]),0);return aggregation==='rms'?Math.sqrt(sum):sum;
}
export function healthFromBurden(b,gamma=1){if(b===null)return null;if(typeof b!=='number'||!Number.isFinite(b)||b<0||b>1||typeof gamma!=='number'||!Number.isFinite(gamma)||gamma<.5||gamma>2)throw Error('Invalid burden or gamma');return Math.max(0,Math.min(100,100*(1-b**gamma)));}
export function scoreParameter(id,input,calibration=DEFAULT_CALIBRATION,scope=null){
 validateCalibration(calibration);const def=PARAMETERS[id];const allowed=scope??Object.keys(def.regions);if(!allowed.length||allowed.some(r=>!Object.hasOwn(def.regions,r))||new Set(allowed).size!==allowed.length)throw Error('Invalid scoring scope '+id);
 const eligible=allowed.filter(r=>input.regions[r]?.state==='observed');
 if(!eligible.length||(def.require_all_regions&&eligible.length!==Object.keys(def.regions).length))return {score:null,burden:null,regions:eligible,regional_burdens:{},coverage:0,reason:input.summary||'Required skin not visible'};
 const den=eligible.reduce((s,r)=>s+def.regions[r],0),regional=Object.fromEntries(eligible.map(r=>[r,combineComponents(id,input.regions[r].components,calibration.aggregation)]));
 const value=eligible.reduce((s,r)=>s+def.regions[r]/den*(calibration.aggregation==='rms'?regional[r]**2:regional[r]),0);
 const burden=calibration.aggregation==='rms'?Math.sqrt(value):value;
 return {score:healthFromBurden(burden,calibration.gamma[id]),burden,regions:eligible,regional_burdens:regional,coverage:den,reason:null};
}
const CORE={active_inflammatory_acne:['visual_acne',['papules_pustules','deep_inflammatory_lesions']],comedonal_congestion:['visual_acne',['comedonal_burden']],oiliness:['skin_sebum'],erythema_redness:['vascularity_redness'],barrier_stress:['barrier_health_sensitivity'],visual_dehydration:['skin_hydration'],pore_visibility:['texture_open_pores',['pores_congestion']],texture_roughness:['texture_open_pores',['coarse_unevenness']],visible_pigmentation:['superficial_pigmentation'],underlying_pigment_support:['superficial_pigmentation'],luminosity_loss:['skin_luminosity_glow'],fine_line_visibility:['superficial_wrinkles'],visible_laxity:['jawline_sagging'],firmness_appearance_loss:['skin_firmness_elasticity'],peri_orbital_concern:['peri_orbital_health'],lip_pigmentation:['lip_pigmentation']};
export function buildRegionalRun(input,options={}){
 const m=decodeMeasurements(input),cal=validateCalibration(options.calibration??DEFAULT_CALIBRATION),calId=calibrationIdentity(cal),parameters={},core={},features={};
 for(const id of IDS){const p=m.parameters[id],out=scoreParameter(id,p,cal),available=out.score!==null,confidence=available?Math.min(...out.regions.map(r=>p.regions[r].confidence)):0;
 parameters[id]={parameter_id:id,display_score_1_to_100:available?Math.round(out.score):null,display_score_0_to_100:available?Math.round(out.score):null,internal_burden_score_1_to_100:available?1+99*(1-out.score/100):null,display_polarity:'higher_is_better',display_band:!available?'not_scored':out.score>=85?'excellent':out.score>=70?'good':out.score>=50?'moderate':'needs_attention',assessment_status:available?'assessed_visible_regions':'not_assessable',client_observation:p.summary,data_quality:{confidence_0_1:confidence,is_estimated:true,estimation_basis:'regional_visual_components',supporting_regions:out.regions,supporting_modes:[...new Set(out.regions.flatMap(r=>p.regions[r].modes))],coverage_fraction:out.coverage,treatment_priority_multiplier:1,unavailable_reason:out.reason},source_components:{},regional_health_scores_1_to_100:Object.fromEntries(Object.entries(out.regional_burdens).map(([r,b])=>[r,healthFromBurden(b,cal.gamma[id])])),calibration:{version:FORMULA_VERSION,configuration_hash:calId,status:cal.status,unrounded_health_1_to_100:out.score,unrounded_health_0_to_100:out.score,calibrated_concern_0_to_1:available?1-out.score/100:null,raw_component_burden_0_to_1:out.burden,component_weights:PARAMETERS[id].components,region_weights:PARAMETERS[id].regions,aggregation:cal.aggregation,gamma:cal.gamma[id],population_percentile:false,measurement_confidence_changes_score:false}};
 }
 for(const[id,[pid,sub]]of Object.entries(CORE)){const p=parameters[pid],me=m.parameters[pid],regional={};
 if(p.assessment_status!=='not_assessable'&&id!=='underlying_pigment_support')for(const r of p.data_quality.supporting_regions){const b=sub?Math.max(...sub.map(k=>me.regions[r].components[k])):1-p.regional_health_scores_1_to_100[r]/100;for(const z of REGIONS[r])regional[z]=b;}
 const vals=Object.values(regional),burden=vals.length?(sub?Math.sqrt(vals.reduce((s,x)=>s+x*x,0)/vals.length):p.calibration.calibrated_concern_0_to_1):null;
 const ranked=Object.keys(regional).sort((a,b)=>regional[b]-regional[a]||a.localeCompare(b));const q=p.data_quality.confidence_0_1;
 core[id]={feature_id:id,assessment_status:burden===null?'not_assessable':'assessable',global_burden_score_1_to_100:burden===null?null:1+99*burden,raw_normalized_burden_0_to_1:burden,guarded_normalized_burden_0_to_1:burden,zone_scores_1_to_100:Object.fromEntries(Object.entries(regional).map(([z,b])=>[z,1+99*b])),zone_normalized_burdens_0_to_1:regional,dominant_zones:ranked.slice(0,3),peak_zone:ranked[0]??null,aggregation_details:{method:sub?'named_visual_component':'canonical_component_parameter',source_parameter:pid,regional_ranking_available:true},guardrails_applied:[],measurement_sensitivity:'continuous',score_reliability:{score_1_to_100:burden===null?0:q*100,tier:q>=.85?'high':q>=.6?'moderate':'low',reasons:burden===null?['not_assessable']:[]},treatment_evidence_v37:{confidence_0_1:q,priority_multiplier:1,linked_parameters:[pid]},measurement_provenance:{version:VERSION,source_parameter:pid,uses_same_primitives_as_client_score:true,limitation:id==='underlying_pigment_support'?'UV-only burden is not established by appearance calibration':null}};
 features[id]={feature_id:id,zones:Object.fromEntries(ranked.map(z=>[z,{assessment_status:'assessable',visibility_fraction_0_to_100:100,components:{},mode_agreement:'not_quantified',artifact_flags:[],evidence_summary:me.summary}])),global_artifact_flags:[],global_evidence_summary:me.summary};
 }
 const skinType={label:m.skin_type.label,modifiers:[],evidence:{source:'visible_pattern',description:m.skin_type.observation},data_quality:{confidence_0_1:m.skin_type.confidence,is_estimated:true}};parameters.skin_type={parameter_id:'skin_type',display_label:skinType.label,value_type:'label',data_quality:skinType.data_quality};
 const scan={scan_id:options.scanId??'unspecified',image_set_hash:options.imageSetHash??null,capture_type:options.captureType??'baseline',paired_baseline_scan_id:options.pairedBaselineScanId??null,modes_received:options.modesReceived??[]};
 const execution={mapper_version:VERSION,calibration_version:FORMULA_VERSION,formula_config_version:FORMULA_VERSION,calibration_configuration_hash:calId,calibration_status:cal.status,created_at_iso:new Date().toISOString(),immutable_assessment:true,history_excluded_from_image_scoring:true};
 const state={schema_version:SKIN_STATE_SCHEMA_VERSION,zone_atlas_version:FACE_ZONE_ATLAS_VERSION,scan,scoring_execution:execution,component_calibration:cal,regional_measurements:m,core_features:core,derived_report_parameters:parameters,skin_type:skinType,morphology_exclusion_summary:{reconciliation_action_count:0,reconciliation_audit:[]}};
 return {skin_state:state,evidence_packet:{schema_version:VISION_EVIDENCE_SCHEMA_VERSION,zone_atlas_version:FACE_ZONE_ATLAS_VERSION,scan,model_execution:{model_version:options.modelVersion??'manual_or_test',prompt_version:VERSION,created_at_iso:execution.created_at_iso},features,regional_measurements:m}};
}
