// V3.18 candidate: explicit appearance components; no patient-specific runtime scores.
export const VERSION='aia_component_measurement_v3.18.0';
export const FORMULA_VERSION='aia_component_rms_v3.18.0';
export const COMPARISON_VERSION='aia_component_comparison_v3.18.0';
export const MODES=['white','surface_polarized','subsurface_polarized','red','woods_uv'];
export const FACE={forehead:.25,cheek_left:.25,cheek_right:.25,nose:.15,lower_face:.10};
export const REGIONS={forehead:['forehead_left','forehead_center','forehead_right'],cheek_left:['malar_medial_left','cheek_lateral_left'],cheek_right:['malar_medial_right','cheek_lateral_right'],nose:['nose'],lower_face:['perioral','chin'],eye_left:['peri_orbital_left'],eye_right:['peri_orbital_right'],lip_upper:['upper_lip'],lip_lower:['lower_lip'],jaw_left:['jawline_left'],jaw_right:['jawline_right']};
const p=(label,components,definitions,{regions=FACE,modes=['white','surface_polarized'],hold=[],all=false}={})=>({label,components,definitions,regions,modes,hold,require_all_regions:all});
export const PARAMETERS={
 barrier_health_sensitivity:p('Barrier Health',{surface_disruption:.40,dry_tight_appearance:.35,irritated_blotchiness:.25},['Adherent scale, lifted skin edges or disrupted skin; not loose product or cotton.','Papery, visibly tight dry surface; absence of flakes alone does not establish excellent appearance.','Diffuse irritated-looking blotchiness; do not count only individual acne lesions.'],{modes:['white','surface_polarized','subsurface_polarized']}),
 visual_acne:p('Visual Acne',{comedonal_burden:.40,papules_pustules:.40,deep_inflammatory_lesions:.20},['Conspicuous blackheads/whiteheads and their pattern; exclude hairs, ordinary pores and sebaceous filaments when distinguishable.','Raised inflammatory papules/pustules, including visible surrounding inflammation. Do not infer every flat brown mark is active acne.','Visibly deeper inflamed raised lesions; no palpation-based diagnosis.']),
 skin_sebum:p('Skin Sebum Balance',{greasy_film:.60,uneven_oily_distribution:.40},['Concentrated greasy film/shine; product glints alone do not establish excess oil.','Disproportionate oily T-zone versus cheeks; naturally matte skin is not automatically deficient.'],{regions:{forehead:.30,nose:.35,cheek_left:.15,cheek_right:.15,lower_face:.05}}),
 vascularity_redness:p('Vascularity / Redness',{diffuse_redness:.65,localized_redness_vessels:.35},['Visible diffuse redness relative to surrounding natural tone.','Conspicuous localized redness/vascular pattern; exclude pigment and anatomical shadow.'],{modes:['white','subsurface_polarized']}),
 skin_hydration:p('Skin Hydration Appearance',{crepiness_microlines:.40,superficial_plumpness_deficit:.35,dry_patches_flaking:.25},['Papery crepiness and fine superficial dehydration-type lines; exclude fixed wrinkles.','Lack of supple-looking superficial fullness; exclude normal facial anatomy, hollows, fat volume and swelling.','Visible rough dry patches/adherent flakes, not product particles. Gloss alone neither proves nor disproves hydration.']),
 skin_luminosity_glow:p('Skin Luminosity / Glow',{diffuse_dullness:.50,uneven_luminosity:.25,pigment_interruption:.25},['Broad dull/gray appearance relative to natural tone; oily highlights are not diffuse luminosity.','Patchy broad luminosity at ordinary face-view scale, excluding anatomical shadows.','How visible pigment interrupts luminosity; not the pigment load in an enhanced mode.'],{modes:['white','surface_polarized','subsurface_polarized']}),
 superficial_pigmentation:p('Superficial Pigmentation',{patch_contrast:.60,mottling:.40},['Contrast of identifiable brown patches with nearby same-region skin in white light. Natural complexion is not pathology.','Broader uneven pigment distribution; exclude hair, pore dots, moles and redness. Follow the SAME patches in comparisons.'],{modes:['white','subsurface_polarized']}),
 peri_orbital_health:p('Peri-Orbital Health',{discoloration:.45,hollow_puffy_appearance:.35,fine_crepiness:.20},['Visible brown/vascular discoloration; exclude eyelid cosmetics.','Apparent hollowing or puffiness under matched head pose; not evidence of changed anatomy.','Fine papery peri-orbital surface lines, excluding lash/eyelid shadows.'],{regions:{eye_left:.5,eye_right:.5},modes:['white','surface_polarized','subsurface_polarized']}),
 lip_pigmentation:p('Lip Pigmentation',{uneven_pigment:.70,patch_border_contrast:.30},['Excess uneven lip pigment relative to natural lip tone, excluding lipstick, dryness and shine.','Conspicuous pigment patch/border contrast, excluding constitutional tone and shadow.'],{regions:{lip_upper:.5,lip_lower:.5},modes:['white','subsurface_polarized'],all:true}),
 texture_open_pores:p('Texture + Open Pores',{pores_congestion:.40,pits_scars:.35,coarse_unevenness:.25},['Visible pore openings and congestion; judge normal-view conspicuity using crop to verify morphology.','Depressed pits/scars; distinguish from pores, dots and hairs.','Coarse uneven surface outside discrete pore/scar depressions.'],{hold:['pits_scars']}),
 superficial_wrinkles:p('Superficial Wrinkles',{fixed_lines:.75,dehydration_lines:.25},['Fixed visible lines/folds under comparable expression and pose.','Fine superficial dehydration-type lines, excluding fixed folds.'],{hold:['fixed_lines']}),
 jawline_sagging:p('Jawline',{jowl_prejowl:.60,lower_face_drape:.40},['Visible jowl/pre-jowl contour disruption. Beard-covered contour is unavailable.','Visible lower-face drape, excluding head tilt and constitutional shape.'],{regions:{jaw_left:.5,jaw_right:.5},modes:['white'],hold:['jowl_prejowl','lower_face_drape'],all:true}),
 skin_firmness_elasticity:p('Skin Firmness Appearance',{visible_laxity:.80,superficial_tautness_deficit:.20},['Visible cheek/lower-face laxity; not mechanical elasticity or collagen measurement.','Superficial tautness appearance, excluding swelling, pose and structural contour.'],{regions:{cheek_left:.3,cheek_right:.3,jaw_left:.2,jaw_right:.2},hold:['visible_laxity']}),
 textural_radiance:p('Textural Radiance',{fine_grain:.45,reflection_interruption:.35,microshadows:.20},['Fine surface grain at normal-view scale; no direct additional pore/scar penalty.','Interrupted fine surface reflection, excluding glare and pigmentation darkness.','Fine texture-related microshadows; exclude anatomical shadows, beard and fixed scar pits.'])
};
export const IDS=Object.keys(PARAMETERS);
export const ANCHORS={0:'No meaningful deficit, supported by positively interpretable skin.',.25:'Slight but identifiable visible deficit.',.5:'Clearly noticeable cosmetic deficit at ordinary face-view scale.',.75:'Marked deficit dominating the relevant appearance.',1:'Extreme appearance deficit within this component definition.'};
export const CLINICAL_STATUS='candidate_component_definitions_and_weights; not_live_model_calibrated';
// No numerical coefficients are fitted to unblinded manual simulation in this release.
export const DEFAULT_CALIBRATION=Object.freeze({version:FORMULA_VERSION,status:CLINICAL_STATUS,aggregation:'rms',gamma:Object.freeze(Object.fromEntries(IDS.map(id=>[id,1])))});
export const INSTRUCTIONS=`Measure visible cosmetic appearance, not disease severity, population percentile, instrument hydration or elasticity. Images are actual five-mode captures. White light defines visible impact; polarized modes clarify morphology, not an extra penalty for invisible findings. Red/UV are contextual; do not numerically average brightness across modes. Do not infer treatment success or output overall parameter scores. Use the exact requested component and region IDs. A score of severity 0 requires visible positive evidence; missing skin is null, never healthy. Inspect all allowed regions including observed absence of findings. Grade each component continuously from 0 to 1, referencing the anchors; two decimal places suffice. Describe concrete findings before grading. A clearly visible cosmetic deficit can be moderate even without severe disease. Natural darker skin or lips are not inherently deficient. A crop verifies morphology; its magnification must not inflate ordinary-view prominence. Do not invent pixel counts, melanin readings or geometric measurements. Distinguish residue, oil, skin flaking, pores, comedones, scars, pigment and inflammation. Skin can have conspicuous pores with comparatively good fine radiance, and adequate hydration with poor glow. Do not copy one score into adjacent components. Lipstick or an obscured upper lip makes whole lip pigmentation unavailable. Hidden jaw contour is unavailable. Exclude ill-lit/foreshortened skin when uninterpretable for this parameter, but do not assume lighting changes just to discount observed improvement. Region evidence must identify the visible support or reason for exclusion. Confidence is metadata, never a multiplier of burden, gain or treatment priority. Keep region evidence under 20 words and parameter summary under 25 words. Do not repeat the rubric.`;
