import {IDS,PARAMETERS,FORMULA_VERSION} from './componentContractV318.js';
import {recommendConcernsV38} from './concernRecommendationsV38.js';
const keys=['barrier_health_sensitivity','visual_acne_grading','skin_sebum_content','vascularity_redness_profiling','skin_hydration_score','skin_luminosity_glow_index','superficial_pigmentation_score','periorbital_health','lip_pigmentation','texture_open_pores_scoring','superficial_wrinkles_scoring','jawline_sagging_score','skin_firmness_elasticity_index','textural_radiance_index'];
export const PARAMETER_META=Object.fromEntries(IDS.map((id,i)=>[id,{legacy_key:keys[i],label:PARAMETERS[id].label}]));
export function buildSkinAnalysisReportV3({skinState,client={},clinic={},imageAssets=null,statedConcerns=[]}){
 const cards=IDS.map(id=>{const p=skinState.derived_report_parameters[id];return {parameter_id:id,label:PARAMETERS[id].label,value_type:p.display_score_1_to_100===null?'unavailable':'score',display_label:p.display_score_1_to_100===null?'Not scored':null,client_health_score_1_to_100:p.display_score_1_to_100,concern_burden_score_1_to_100:p.internal_burden_score_1_to_100,display_polarity:'higher_is_better',original_parameter:p};});
 cards.unshift({parameter_id:'skin_type',label:'Skin Type',value_type:'label',display_label:skinState.skin_type.label});const numeric=cards.filter(c=>c.value_type==='score');
 return {report_version:FORMULA_VERSION,formal_report_type:'ai_skin_analysis_report',client,clinic,scan:skinState.scan,overall_skin_health_score_1_to_100:numeric.length?Math.round(numeric.reduce((s,c)=>s+c.client_health_score_1_to_100,0)/numeric.length):null,stated_concerns:statedConcerns,primary_client_assessment:{parameter_count:15,parameter_cards:cards,strongest_parameters:[...numeric].sort((a,b)=>b.client_health_score_1_to_100-a.client_health_score_1_to_100).slice(0,4),highest_opportunities:[...numeric].sort((a,b)=>a.client_health_score_1_to_100-b.client_health_score_1_to_100).slice(0,5)},five_mode_images:imageAssets,clinical_support_layer:{visible_to_client_by_default:false,core_features:skinState.core_features},report_rules:{numeric_parameters:14,skin_type_is_not_numeric:true,missing_is_not_zero:true}};
}
export function buildLegacyDiagnosisV34({skinAnalysisReport,skinState}){
 const diagnosis_report={skin_type:{parameter_id:'skin_type',parameter_name:'Skin Type Classification',score_or_label:skinState.skin_type.label,score_scale:'label',score_explanation:skinState.skin_type.evidence.description,possible_causes:[],affected_area_image:4}};
 for(const id of IDS){const p=skinState.derived_report_parameters[id];diagnosis_report[PARAMETER_META[id].legacy_key]={parameter_id:id,parameter_name:PARAMETERS[id].label,description:'Visible appearance score; higher is better.',client_description:p.client_observation,score_or_label:p.display_score_1_to_100,display_label:p.display_score_1_to_100===null?'Not scored':null,score_scale:'0_to_100_client_appearance_higher_is_better',score_semantics:'appearance',score_polarity:'higher_is_better',ideal_score_direction:id==='skin_sebum'?'balance':'increase',comparison_mode:'direct_numeric',score_explanation:p.client_observation,affected_area_image:4,affected_zones:p.data_quality.supporting_regions,possible_causes:[],calibration_version:FORMULA_VERSION,calibration_audit:p.calibration,data_quality:p.data_quality,normalized_burden_0_to_1:p.calibration.calibrated_concern_0_to_1,v3_4_client_health_score_1_to_100:p.display_score_1_to_100,v3_4_concern_burden_score_1_to_100:p.internal_burden_score_1_to_100};}
 const suggestions=recommendConcernsV38(skinState).map(s=>({...s,parameter:PARAMETERS[s.parameter_id].label,score_scale:'0_to_100_client_appearance_higher_is_better',reason_for_selection:'Expected visible benefit; primary concerns can be changed by the client.',short_description:skinState.derived_report_parameters[s.parameter_id].client_observation}));
 return {diagnosis_report,treatable_concerns_summary:{description:'Concerns ranked by expected visible improvement; primary selections remain editable.',parameters_with_abnormal_scores:suggestions},v3_4_report:skinAnalysisReport,v3_4_skin_state:skinState};
}
