import {VERSION as MEASUREMENT_VERSION,COMPARISON_VERSION,FORMULA_VERSION,PARAMETERS,IDS,DEFAULT_CALIBRATION} from './componentContractV318.js';
import {wireSchema,measurementPrompt,decodeMeasurements,exact} from './componentMeasurementV318.js';
import {buildRegionalRun,scoreParameter,calibrationIdentity} from './componentScoringV318.js';
import {PARAMETER_META} from './componentReportV318.js';
export const VERSION=COMPARISON_VERSION;
export function comparisonFormat(){const schema=wireSchema();for(const id of IDS)for(const row of Object.values(schema.properties.parameters.properties[id].properties.regions.properties)){Object.assign(row.properties,{matched_region:{type:'boolean'},pose_comparable:{type:'boolean'},before_evidence:{type:'string'}});row.required=Object.keys(row.properties);}return {type:'json_schema',name:'paired_components_v318',strict:true,schema};}
export function comparisonPrompt(){return measurementPrompt()+`\nTASK OVERRIDE: PAIRED COMPARISON, not a new independent whole-face assessment. Inspect reference and post images together. Saved baseline component values are fixed. Describe the before and after finding in the SAME anatomical region, then return the observed component endpoints anchored to the saved baseline. Do not return parameter scores, deltas or stable labels. A component may change substantially if the actual visible appearance traverses that much of the defined severity scale. No expected gain, generic improvement bonus or confidence scaling. Mark matched_region false when correspondence/visibility does not permit comparison. Mark pose_comparable false when pose/expression differs sufficiently to compromise contour/hollow interpretation; this need not invalidate colour or fine texture comparisons. Return current after-region observations even for newly visible skin, without inventing a baseline. Backend holds fixed lines, scar pits, jaw structure and structural laxity during this immediate workflow; superficial tautness and dehydration lines can change. Product residue alone is not flaking. Maintain skin_type from baseline. No labels or target scores from calibration cases are supplied.`;}
export function baselineContext(state){if(state?.regional_measurements?.version!==MEASUREMENT_VERSION||state.scoring_execution?.formula_config_version!==FORMULA_VERSION)throw Error('V3.18 requires a V3.18 baseline from the saved BEFORE images. Preserve old reports; do not relabel old states.');const cal=state.component_calibration??DEFAULT_CALIBRATION;if(state.scoring_execution.calibration_configuration_hash!==calibrationIdentity(cal))throw Error('Baseline calibration hash mismatch');return {reference_scan_id:state.scan.scan_id,reference:state.regional_measurements,calibration_configuration_hash:state.scoring_execution.calibration_configuration_hash};}
export function stableComparison(state){baselineContext(state);const w=structuredClone(state.regional_measurements);for(const id of IDS)for(const row of Object.values(w.parameters[id].regions))Object.assign(row,{matched_region:row.state==='observed',pose_comparable:true,before_evidence:'Identical source captures; reference retained.'});return w;}
export function applyComparison(baseline,input,options={}){
 const original=baseline.skin_state;baselineContext(original);const cal=original.component_calibration??DEFAULT_CALIBRATION;
 if(options.calibration&&calibrationIdentity(options.calibration)!==calibrationIdentity(cal))throw Error('Comparison cannot change calibration coefficients');
 const current=structuredClone(input),audit={version:VERSION,parameters:{}};
 exact(current,['version','parameters','skin_type'],'comparison');exact(current.parameters,IDS,'comparison parameters');
 const annotations={};
 for(const id of IDS){const def=PARAMETERS[id];exact(current.parameters[id],['summary','regions'],id);exact(current.parameters[id].regions,Object.keys(def.regions),id+'.regions');annotations[id]={};
 for(const[r,row]of Object.entries(current.parameters[id].regions)){exact(row,['state','confidence','modes','evidence','components','matched_region','pose_comparable','before_evidence'],id+'.'+r);if(typeof row.matched_region!=='boolean'||typeof row.pose_comparable!=='boolean'||typeof row.before_evidence!=='string'||!row.before_evidence.trim())throw Error('Missing paired support '+id+'.'+r);
 annotations[id][r]={matched_region:row.matched_region,pose_comparable:row.pose_comparable,before_evidence:row.before_evidence,after_evidence:row.evidence,held_components:[]};delete row.matched_region;delete row.pose_comparable;delete row.before_evidence;
 }}
 decodeMeasurements(current); // Validate BEFORE applying structural carries: never sanitize malformed values.
 current.skin_type=structuredClone(original.regional_measurements.skin_type);
 for(const id of IDS){const def=PARAMETERS[id],before=original.regional_measurements.parameters[id];
 for(const[r,row]of Object.entries(current.parameters[id].regions)){const b=before.regions[r],a=annotations[id][r];if(b.state!=='observed'||row.state!=='observed')continue;
 const held=[...def.hold];if(id==='peri_orbital_health'&&!a.pose_comparable)held.push('hollow_puffy_appearance');if(id==='skin_firmness_elasticity'&&!a.pose_comparable)held.push('superficial_tautness_deficit');
 for(const k of held){a.held_components.push({component:k,proposed_after:row.components[k],retained_reference:b.components[k],reason:def.hold.includes(k)?'immediate_structural_hold':'pose_not_comparable'});row.components[k]=b.components[k];}
 }
 }
 const run=buildRegionalRun(current,{...options,calibration:cal});const rows={},display={};
 for(const id of IDS){const b=original.regional_measurements.parameters[id],a=current.parameters[id],old=scoreParameter(id,b,cal),now=scoreParameter(id,a,cal);const common=old.regions.filter(r=>a.regions[r].state==='observed'&&annotations[id][r].matched_region);
 const complete=old.score!==null&&common.length===old.regions.length;
 const commonBefore=common.length?scoreParameter(id,b,cal,common):null,commonAfter=common.length?scoreParameter(id,a,cal,common):null;
 const rawBefore=old.score,rawAfter=complete?commonAfter.score:null,rawDelta=rawAfter===null?null:rawAfter-rawBefore;
 const prior=Number.isFinite(original.client_display_state?.[id])?original.client_display_state[id]:rawBefore===null?null:Math.round(rawBefore);
 const shown=prior===null?(now.score===null?null:Math.round(now.score)):rawAfter===null?prior:Math.max(prior,Math.round(rawAfter));
 const result=prior===null?'not_compared':shown>prior?'improved':'stable';const newly=prior===null&&shown!==null;
 display[id]=shown;
 audit.parameters[id]={status:complete?'compared':newly?'new_reference':'not_comparable',reference_score:rawBefore,after_score_same_scope:rawAfter,raw_delta:rawDelta,current_available_region_score:now.score,baseline_scope:old.regions,common_regions:common,common_region_delta:commonBefore?.score!==null&&commonBefore?.score!==undefined&&commonAfter?.score!==null?commonAfter.score-commonBefore.score:null,regions:annotations[id],confidence_changes_score:false,gain_cap:null,minimum_gain_gate:null};
 rows[PARAMETER_META[id].legacy_key]={parameter_id:id,parameter_name:PARAMETERS[id].label,before_treatment_score_or_label:prior,post_treatment_score_or_label:shown,score_scale:'0_to_100_client_appearance_higher_is_better',result,patient_facing_change_points:prior===null?null:shown-prior,score_explanation:newly?'First visible assessment; no before/after improvement is calculated.':shown===null?'Not scored: required skin is obscured or uninterpretable.':result==='improved'?`Visible appearance improved by ${shown-prior} points.`:'The displayed score remains stable.',raw_comparison_result_internal:rawDelta===null?'not_comparable':rawDelta>0?'improved':rawDelta<0?'declined':'stable',base_post_score_or_label_internal:rawAfter,comparison_mode:'paired_components_same_equations',transient_reactivity_note:id==='vascularity_redness'&&rawDelta!==null&&rawDelta<0?'Post-treatment redness may be temporary; persistent or worsening redness needs clinical review.':'none',measurement_status_internal:audit.parameters[id].status,raw:{before_health_score_1_to_100:rawBefore,after_health_score_1_to_100:rawAfter,raw_delta:rawDelta,shown_delta:prior===null?null:shown-prior,comparison_status:audit.parameters[id].status},v3_4_before_health_score_1_to_100:rawBefore,v3_4_after_health_score_1_to_100:rawAfter,v3_4_health_change_1_to_100:rawDelta};
 }
 rows.skin_type={parameter_id:'skin_type',parameter_name:'Skin Type',before_treatment_score_or_label:original.skin_type.label,post_treatment_score_or_label:original.skin_type.label,result:'stable',score_scale:'label',score_explanation:'Skin type is carried forward.'};
 run.skin_state.client_display_state=display;run.skin_state.comparative_audit=audit;run.evidence_packet.comparative_audit=audit;
 run.skin_state.scoring_execution={...run.skin_state.scoring_execution,comparison_version:VERSION,reference_rescored:false,inference_architecture:'paired_regional_components_same_formula',history_excluded_from_image_scoring:false};
 run.skin_state.regional_measurement_provenance={type:'paired_endpoints_with_explicit_structural_carries',audit:'comparative_audit',reference_scan_id:original.scan.scan_id};
 return {post_run:run,post_diagnosis:{reassessment:rows,metadata:{comparison_version:VERSION,reference_rescored:false,display_policy:'Lower estimates carry the previous displayed score as stable. Raw signed measurements and scope changes remain in the clinical record.',planning_score_source:'post_run.skin_state, never client_display_state',score_counts:Object.fromEntries(['improved','stable','not_compared'].map(status=>[status,Object.values(rows).filter(r=>r.parameter_id!=='skin_type'&&r.result===status).length]))}},comparative_audit:audit};
}
