import assert from 'node:assert/strict'
import {pathToFileURL} from 'node:url'
import {FEATURES,PARAMETERS,GROUPS,MEASUREMENT_VERSION,impactToHealth} from './visibleImpactRubricV315.js'
import {measurementPrompt,measurementFormat,decodeMeasurements} from './regionalMeasurementV310.js'
import {buildRegionalRun} from './regionalScoringV310.js'
import {buildSkinAnalysisReportV3} from './buildSkinAnalysisReportV3.js'
import {buildLegacyDiagnosisV34} from './legacyFacialAdapterV34.js'
export function fixture(level=2){return {version:MEASUREMENT_VERSION,regions:Object.fromEntries(Object.keys(GROUPS).map(g=>[g,{visible_fraction:1,obstruction_note:''}])),features:Object.fromEntries(Object.entries(FEATURES).map(([f,c])=>[f,{state:'observed',impact_level:level,confidence:.9,regions:[c.regions[0]],evidence:'Synthetic visible evidence.',extent_note:'Localized synthetic example.'}])),parameters:Object.fromEntries(Object.entries(PARAMETERS).map(([id,p])=>[id,{state:'observed',impact_level:level,confidence:.9,supporting_features:p.features,dominant_features:[p.features[0]],rationale:'Synthetic overall appearance, not patient evidence.'}])),skin_type:{label:'balanced',confidence:.9,observation:'Synthetic pattern'}}}
export function selfTest(){
 const checks=[],check=(s,f)=>{f();checks.push(s)},opts={scanId:'fixture',imageSetHash:'fixture',modelVersion:'mock'}
 const run=v=>buildRegionalRun(v,opts).skin_state
 check('Fixed anchor conversion and endpoints',()=>{assert.equal(impactToHealth(0),100);assert.equal(impactToHealth(1),80);assert.equal(impactToHealth(2),60);assert.equal(impactToHealth(2.5),50);assert.equal(impactToHealth(5),1)})
 check('Continuous integer scores 61–77, not bucket midpoints',()=>{for(let s=61;s<=77;s++)assert(Math.abs(impactToHealth((100-s)/20)-s)<1e-9)})
 check('Same observations give identical scores',()=>assert.deepEqual(run(fixture()).derived_report_parameters,run(fixture()).derived_report_parameters))
 check('Confidence changes do not change measured scores or priority multipliers',()=>{const a=run(fixture()),f=fixture();for(const r of Object.values(f.features))r.confidence=.2;for(const r of Object.values(f.parameters))r.confidence=.2;const b=run(f);for(const id of Object.keys(PARAMETERS)){assert.equal(a.derived_report_parameters[id].display_score_1_to_100,b.derived_report_parameters[id].display_score_1_to_100);assert.equal(b.derived_report_parameters[id].data_quality.treatment_priority_multiplier,1)}})
 check('Area notes do not numerically dilute global visible impact',()=>{const a=fixture(),b=fixture();for(const r of Object.values(b.features))r.extent_note='Tiny localized region';assert.deepEqual(run(a).derived_report_parameters.texture_open_pores.display_score_1_to_100,run(b).derived_report_parameters.texture_open_pores.display_score_1_to_100)})
 check('Partial beard cover normalizes estimate state without numerical changes',()=>{const f=fixture();f.regions.forehead_left.visible_fraction=.3;const d=decodeMeasurements(f);assert.equal(d.features.dehydration_lines.state,'supported_estimate');assert.equal(d.features.dehydration_lines.impact_level,2);assert.equal(d.features.dehydration_lines.confidence,.55)})
 check('Unsupported zero from case 58 becomes unavailable, never ideal',()=>{const f=fixture();f.features.dehydration_lines={...f.features.dehydration_lines,impact_level:0,confidence:.73,evidence:'No supported observation'};const d=decodeMeasurements(f);assert.equal(d.features.dehydration_lines.impact_level,null);assert.equal(d.features.dehydration_lines.state,'unavailable');assert(!d.parameters.skin_hydration.supporting_features.includes('dehydration_lines'))})
 check('Fully unsupported jawline cannot become 100',()=>{const f=fixture();for(const id of PARAMETERS.jawline_sagging.features)Object.assign(f.features[id],{impact_level:0,evidence:'Beard obscures mandibular contour.'});assert.throws(()=>run(f),/No supported numerical estimate/)})
 check('Supported jawline estimate is accepted with uncertainty separate',()=>{const f=fixture();f.parameters.jawline_sagging.impact_level=.5;f.parameters.jawline_sagging.state='supported_estimate';f.parameters.jawline_sagging.rationale='Exposed lower-cheek contour supports a limited contour estimate.';assert.equal(run(f).derived_report_parameters.jawline_sagging.display_score_1_to_100,90)})
 check('Unavailable component need not block a parameter with remaining support',()=>{const f=fixture();Object.assign(f.features.flaking,{state:'unavailable',impact_level:null,confidence:0,regions:[],evidence:'No supported observation'});assert.equal(run(f).derived_report_parameters.skin_hydration.display_score_1_to_100,60)})
 check('Malformed and old-version data rejected',()=>{for(const edit of [f=>f.version='aia_visual_baseline_measurement_v3.14.0',f=>f.parameters.skin_hydration.impact_level=NaN,f=>f.parameters.skin_hydration.impact_level=6,f=>delete f.parameters.skin_hydration]){const f=fixture();edit(f);assert.throws(()=>decodeMeasurements(f))}})
 check('Perfect parameter cannot contradict nonzero supported findings',()=>{const f=fixture();f.parameters.skin_hydration.impact_level=0;f.parameters.skin_hydration.dominant_features=[];assert.throws(()=>decodeMeasurements(f),/Perfect impact contradicts/)})
 check('Concern cannot be manufactured from entirely absent supporting findings',()=>{const f=fixture(0);f.parameters.skin_hydration.impact_level=2;assert.throws(()=>decodeMeasurements(f),/Concern lacks supporting/)})
 check('Input immutable and normalized decode idempotent',()=>{const f=fixture(),saved=structuredClone(f),d=decodeMeasurements(f);assert.deepEqual(f,saved);assert.deepEqual(decodeMeasurements(d),d)})
 check('Canonical report score passes through existing report and diagnosis adapters',()=>{const s=run(fixture()),r=buildSkinAnalysisReportV3({skinState:s});const d=buildLegacyDiagnosisV34({skinState:s,skinAnalysisReport:r});assert(d);for(const c of r.primary_client_assessment.parameter_cards)if(c.parameter_id!=='skin_type')assert.equal(c.client_health_score_1_to_100,60)})
 check('Clinical reference values are not embedded as runtime targets',()=>{const p=measurementPrompt();assert(!p.includes('assessment_58'));assert(!p.includes('clinician_center'));assert(!p.includes('97.724372'))})
 return {ok:true,checks,prompt_characters:measurementPrompt().length,schema_characters:JSON.stringify(measurementFormat()).length,scope:'Synthetic software checks only. No claim of fresh GPT output accuracy or clinical benchmark pass.'}
}
if(import.meta.url===pathToFileURL(process.argv[1]).href)console.log(JSON.stringify(selfTest(),null,2))
